// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Laftrip.iOS
{
	public partial class PopularPhotosViewController : UIViewController
	{
		public PopularPhotosViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
